#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" style of «sed -e» combined with subshells is used
#       to be able to have the full command line in most cases.
#
#       The exception is when «gradle.sh» is called with arguments. In that
#       case the first word of the command line is assumed to be the command
#       (usually «sh»).
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#)}; t=/${t%%/*}             # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started.
        # This is a workaround for bash bug #53747.
        shift                   # out with the old
        set -- "$@" "$arg"      # in with the new
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     temporary files.
#   * For bash/zsh, word-split $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS
#     during assignment.
#   * POSIX shell, do NOT use word-splitting; pass literal strings as arguments.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n://services.gradle.org/distributions/gradle-8.2-bin.zip, arguments are://services.gradle.org/distributions/gradle-8.2-bin.zip fed in://services.gradle.org/distributions/gradle-8.2-bin.zip from the command://services.gradle.org/distributions/gradle-8.2-bin.zip line via://services.gradle.org/distributions/gradle-8.2-bin.zip xargs.://services.gradle.org/distributions/gradle-8.2-bin.zip
# Regardless of eval'ing the result or not, "//services.gradle.org/distributions/gradle-8.2-bin.zip@//services.gradle.org/distributions/gradle-8.2-bin.zip"//services.gradle.org/distributions/gradle-8.2-bin.zip is://services.gradle.org/distributions/gradle-8.2-bin.zip always://services.gradle.org/distributions/gradle-8.2-bin.zip added://services.gradle.org/distributions/gradle-8.2-bin.zip before://services.gradle.org/distributions/gradle-8.2-bin.zip the://services.gradle.org/distributions/gradle-8.2-bin.zip first://services.gradle.org/distributions/gradle-8.2-bin.zip actual://services.gradle.org/distributions/gradle-8.2-bin.zip argument.://services.gradle.org/distributions/gradle-8.2-bin.zip
#
# Arguments://services.gradle.org/distributions/gradle-8.2-bin.zip of://services.gradle.org/distributions/gradle-8.2-bin.zip the://services.gradle.org/distributions/gradle-8.2-bin.zip form://services.gradle.org/distributions/gradle-8.2-bin.zip:"--foo"//services.gradle.org/distributions/gradle-8.2-bin.zip are://services.gradle.org/distributions/gradle-8.2-bin.zip passed://services.gradle.org/distributions/gradle-8.2-bin.zip as://services.gradle.org/distributions/gradle-8.2-bin.zip"--foo",://services.gradle.org/distributions/gradle-8.2-bin.zip arguments://services.gradle.org/distributions/gradle-8.2-bin.zip of://services.gradle.org/distributions/gradle-8.2-bin.zip the://services.gradle.org/distributions/gradle-8.2-bin.zip form://services.gradle.org/distributions/gradle-8.2-bin.zip:"--foo=bar"//services.gradle.org/distributions/gradle-8.2-bin.zip are://services.gradle.org/distributions/gradle-8.2-bin.zip passed://services.gradle.org/distributions/gradle-8.2-bin.zip as://services.gradle.org/distributions/gradle-8.2-bin.zip"--foo=bar".://services.gradle.org/distributions/gradle-8.2-bin.zip
#
# It://services.gradle.org/distributions/gradle-8.2-bin.zip is://services.gradle.org/distributions/gradle-8.2-bin.zip critical://services.gradle.org/distributions/gradle-8.2-bin.zip that://services.gradle.org/distributions/gradle-8.2-bin.zip there://services.gradle.org/distributions/gradle-8.2-bin.zip is://services.gradle.org/distributions/gradle-8.2-bin.zip NO://services.gradle.org/distributions/gradle-8.2-bin.zip sub-shell://services.gradle.org/distributions/gradle-8.2-bin.zip spawned://services.gradle.org/distributions/gradle-8.2-bin.zip here,://services.gradle.org/distributions/gradle-8.2-bin.zip because://services.gradle.org/distributions/gradle-8.2-bin.zip the://services.gradle.org/distributions/gradle-8.2-bin.zip script://services.gradle.org/distributions/gradle-8.2-bin.zip would://services.gradle.org/distributions/gradle-8.2-bin.zip not://services.gradle.org/distributions/gradle-8.2-bin.zip survive://services.gradle.org/distributions/gradle-8.2-bin.zip the://services.gradle.org/distributions/gradle-8.2-bin.zip implicit://services.gradle.org/distributions/gradle-8.2-bin.zip sub-shell://services.gradle.org/distributions/gradle-8.2-bin.zip exit://services.gradle.org/distributions/gradle-8.2-bin.zip (on://services.gradle.org/distributions/gradle-8.2-bin.zip Solaris://services.gradle.org/distributions/gradle-8.2-bin.zip /bin/sh://services.gradle.org/distributions/gradle-8.2-bin.zip,://services.gradle.org/distributions/gradle-8.2-bin.zip at://services.gradle.org/distributions/gradle-8.2-bin.zip least).://services.gradle.org/distributions/gradle-8.2-bin.zip
#
# POSIX://services.gradle.org/distributions/gradle-8.2-bin.zip does://services.gradle.org/distributions/gradle-8.2-bin.zip not://services.gradle.org/distributions/gradle-8.2-bin.zip allow://services.gradle.org/distributions/gradle-8.2-bin.zip the://services.gradle.org/distributions/gradle-8.2-bin.zip use://services.gradle.org/distributions/gradle-8.2-bin.zip of://services.gradle.org/distributions/gradle-8.2-bin.zip "${array[@]}"//services.gradle.org/distributions/gradle-8.2-bin.zip outside://services.gradle.org/distributions/gradle-8.2-bin.zip of://services.gradle.org/distributions/gradle-8.2-bin.zip a://services.gradle.org/distributions/gradle-8.2-bin.zip variable://services.gradle.org/distributions/gradle-8.2-bin.zip assignment://services.gradle.org/distributions/gradle-8.2-bin.zip (in://services.gradle.org/distributions/gradle-8.2-bin.zip parameter://services.gradle.org/distributions/gradle-8.2-bin.zip expansion://services.gradle.org/distributions/gradle-8.2-bin.zip position).://services.gradle.org/distributions/gradle-8.2-bin.zip
# shellcheck disable=SC2046,SC2086,SC2162

# shellcheck disable=SC2034
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

exec "$JAVACMD" "$@"
